---
format:
  html: {toc: true, toc-depth: 4, theme: cosmo, title: LaTeX Demo}
author: Eugen Nesbakken
description: Demonstrating advanced LaTeX features
type: post
date: '2025-01-25'
category: math
tags: [latex, math, demo]

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script><script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" type="text/javascript"></script>

# LaTeX Features Demo

This notebook demonstrates the LaTeX capabilities available in your blog posts.


## Basic Math

Inline math: $E = mc^2$ and $\int_0^\infty e^{-x^2} dx = \frac{\sqrt{\pi}}{2}$

Display math:

$$\sum_{n=1}^{\infty} \frac{1}{n^2} = \frac{\pi^2}{6}$$


## Custom Macros

The following shortcuts are pre-defined:

- Number sets: $\R$, $\N$, $\Z$, $\C$, $\Q$
- Norms and absolute values: $\norm{x}$, $\abs{y}$
- Inner products: $\inner{u}{v}$
- Derivatives: $\dv{f}{x}$, $\pdv{f}{x}$

$$\int_\R f(x) \dd{x} = \inner{f}{g}$$


## Physics Notation

Bra-ket notation:

$$\bra{\psi}\ket{\phi} = \braket{\psi}{\phi}$$

$$\hat{H}\ket{\psi} = E\ket{\psi}$$

Matrices and operators:

$$\mqty(a & b \\ c & d) \vb{x} = \vb{y}$$


## Probability & Statistics

Expected value: $\E{X}$

Variance: $\Var{X}$

Covariance: $\Cov{X}{Y}$

Probability: $\Prob{X > 0}$

$$\E{X} = \int_\R x f(x) \dd{x}$$


## Advanced Equations

Aligned equations:

$$\begin{aligned}
\nabla \cdot \vb{E} &= \frac{\rho}{\epsilon_0} \\
\nabla \cdot \vb{B} &= 0 \\
\nabla \times \vb{E} &= -\pdv{\vb{B}}{t} \\
\nabla \times \vb{B} &= \mu_0\vb{J} + \mu_0\epsilon_0\pdv{\vb{E}}{t}
\end{aligned}$$


## Matrices

$$A = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}$$

$$\det(A - \lambda I) = 0$$


## Code + Math

Here's some Clojure code alongside math:


::: {.sourceClojure}
```clojure
(defn quadratic-formula
  "Solves ax² + bx + c = 0"
  [a b c]
  (let [discriminant (- (* b b) (* 4 a c))
        sqrt-disc (Math/sqrt discriminant)]
    [(/ (+ (- b) sqrt-disc) (* 2 a))
     (/ (- (- b) sqrt-disc) (* 2 a))]))
```
:::



::: {.sourceClojure}
```clojure
(quadratic-formula 1 -5 6)
```
:::



::: {.printedClojure}
```clojure
[3.0 2.0]

```
:::


The quadratic formula:

$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$


## TikZ Diagrams

TikZ diagrams are pre-rendered to PNG for web display.
Use the `tikz` namespace to render diagrams:


::: {.sourceClojure}
```clojure
(tikz/render
  "\\begin{tikzpicture}[node distance=2cm, auto]
    \\node[draw, circle] (A) {$A$};
    \\node[draw, circle, right of=A] (B) {$B$};
    \\node[draw, circle, below of=A] (C) {$C$};
    \\node[draw, circle, below of=B] (D) {$D$};
    \\draw[->] (A) -- node {$f$} (B);
    \\draw[->] (A) -- node[left] {$g$} (C);
    \\draw[->] (B) -- node {$h$} (D);
    \\draw[->] (C) -- node {$k$} (D);
   \\end{tikzpicture}"
  "commutative-diagram"
  :caption "A commutative diagram"
  :width "50%")
```
:::



::: {.callout-important collapse=false}
## Cannot run program "convert": error=2, No such file or directory
error=2, No such file or directory
```
                clojure.core/eval             core.clj: 3232
                              ...                          
             latex-demo/eval34344           REPL Input:     
                              ...                          
                      tikz/render           REPL Input:      (repeats 2 times)
                              ...                          
            clojure.java.shell/sh            shell.clj:   79
            clojure.java.shell/sh            shell.clj:  113
           java.lang.Runtime.exec         Runtime.java:  605
   java.lang.ProcessBuilder.start  ProcessBuilder.java: 1044
   java.lang.ProcessBuilder.start  ProcessBuilder.java: 1076
      java.lang.ProcessImpl.start     ProcessImpl.java:  221
     java.lang.ProcessImpl.<init>     ProcessImpl.java:  290
java.lang.ProcessImpl.forkAndExec     ProcessImpl.java:     
java.io.IOException: error=2, No such file or directory
java.io.IOException: Cannot run program "convert": error=2, No such file or directory


```
:::



```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/eugnes03/personalwebpage/blob/main/notebooks/latex-demo.clj">notebooks/latex-demo.clj</a></small></small></pre></div>
```
