---
format:
  html: {toc: true, toc-depth: 4, theme: cosmo, title: 'Week 1: Random Walks on the General Linear Group of Fp'}
author: Eugen
description: Research Project
type: post
date: '2026-02-17'
category: mathematics
tags: [algebra, probability, representation-theory]

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script><script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" type="text/javascript"></script>

## Introduction

### The General Linear Group and Representations

I am currently taking MA742, taught by Professor Duque Rosero of Boston University. In this latest homework, she has tasked the class to find the irreducible representations of $\GL{2}(\mathbb{F}_p)$.
From this, I was inspired to look more into this group and connect it to other areas that I am studying. This week I want to familiarize myself with some notions of random walks and representations of random walks on finite groups.  
Note, I will be assuming some elementary notions of group theory and probability theory. It is just outside the reach of someone just introduced to the topic. 

### Preliminary Definitions

Firstly, we need some preliminary definitions just to get a sense of the tools and vocabulary we are going to be working with. 

::: {#def-representation.definition}
## Representation
A **representation** of a group is a group homomorphism 
                    $$
                    \rho : G \to \GL (V)
                    $$
                    where $\GL (V)$ is the general linear group with entries from the vector space $V$.
                    
:::

This is a map of maps. $\rho$ is applied to an element $g \in G$, and then to a vector $v \in V$. A good way of thinking about a representation is it is just a matrix that is purely determined by the elements of a group (finite or not).

::: {.remark}
We usually denote 
                   $$
                   \rho_g = \rho(g)
                   $$
                   as $\rho$ applied to an element in $G$.
:::

Just shorthand notation. Now for some definitions of random walks, and the associated operators needed for random walks on groups. 

::: {#def-random-walk.definition}
## Random Walk
Let $(X, \mathcal{X})$ be a measurable state space. A **random walk** on $X$ is a discrete time Markov process such that:
                 \begin{enumerate}
                 \item $\P(X_{n+1} \in A | X_n, X_{n+1}, \dots, X_0) = \P(X_{n+1} \in | X_n)$
                 \end{enumerate}
:::


```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/eugnes03/personalwebpage/blob/main/notebooks/week1.clj">notebooks/week1.clj</a></small></small></pre></div>
```
